# Generated by Django 3.2.12 on 2023-03-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.TextField()),
                ('issues', models.TextField()),
                ('rules', models.TextField()),
                ('analysis', models.TextField()),
                ('conclusion', models.TextField()),
            ],
        ),
    ]
